config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :authors do
    resources :books
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books,  dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
   before_action :set_author, only: [:show, :edit, :update, :destroy]

    def index
        @authors = Author.all
    end

    def show
        @books = @author.books
    end

    def new
        @author = Author.new
    end

    def create
        Author.create(author_params)
        redirect_to authors_path
    end

    def edit
    end

    def update
        @author.update(author_params)
        redirect_to @author
    end

    def destroy
        @author.destroy
        redirect_to authors_path
    end

    private
    def set_author
        @author = Author.find(params[:id])
    end

    def author_params
        params.require(:author).permit(:first_name, :last_name, :number_of_books, :author_birthdate)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_author
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
        @book = @author.books.new
    end

    def create
        @author.books.create(book_params)

        redirect_to @author
    end

    def edit
    end

    def update
        @book.update(book_params)
        redirect_to author_book_path(@author, @book)
    end

    def destroy
        @book.destroy
        redirect_to @author
    end

    private
    def set_author
        @author = Author.find(params[:author_id])
    end

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:name, :pages, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
    <div class="field">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name %>
    </div>

    <div class="field">
        <%= f.label :last_name, "Last Name" %>
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
        <%= f.label :number_of_books, "Number of Books" %>
        <%= f.number_field :number_of_books %>
    </div>

    <div class="field">
        <%= f.label :author_birthdate, "Author Birthdate" %>
        <%= f.datetime_local_field :author_birthdate %>
    </div>

    <%= f.submit "Submit", :class => "button" %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>

app/views/authors/index.html.erb
<h1>All Authors</h1>

<%= link_to "Create New Author", new_author_path %>

<table>
    <tr>
        <th>Name</th>
        <th>Number of Books</th>
        <th>Born</th>
        <th>Actions</th>
    </tr>

    <% @authors.each do |author| %>
        <tr>
        <td><%= link_to("#{author.first_name} #{author.last_name}", author_path(author)) %></td>
        <td><%= author.number_of_books%></td>
        <td><%= "#{author.author_birthdate.strftime("%m/%d/%Y")}" %></td>
        <td>
            <%= link_to "Edit Author", edit_author_path(author) %>
            &nbsp;|&nbsp;
            <%= link_to "Delete Author", author_path(author),
                data: {
                    turbo_method: :delete, 
                    turbo_confirm: "Are you sure you want to delete #{author.first_name} #{author.last_name}?"} %>
        </td>
            
        

        </tr>
    <% end %>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<h1><%= "#{@author.first_name} #{@author.last_name}"  %></h1>
<%= link_to("All Authors", authors_path) %>
<%= link_to("Add New Book", new_author_book_path(@author)) %>

<br>
<br>
<h2>Books:</h2>
<ul>
<% @books.each do |book| %>
    <li class="row">
    <strong><%= link_to(book.name, author_book_path(@author, book)) %> </strong>
    |
    <em><%= book.genre %> </em>
    |
    <em><%= "#{book.pages} pages" %> </em>
    
   
    </li> 
<% end %>
<ul>

app/views/books/edit.html.erb
<h1>Edit <%= " #{@book.name} by #{@author.first_name} #{@author.last_name}"%></h1>

<%= form_for [@author, @book] do |f| %>
<div class="field">
        <%= f.label :name, "Name of Book" %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :pages, "Number of Pages" %>
        <%= f.number_field :pages %>
    </div>

    <div class="field">
        <%= f.label :genre, "Genre" %>
        <%= f.text_field :genre %>
    </div>
    <%= f.submit "Submit" %>
    <% end %>

app/views/books/new.html.erb
<h1>New Book for <%= "#{@author.first_name} #{@author.last_name}"%></h1>

<%= form_for [@author, @book] do |f| %>
<div class="field">
        <%= f.label :name, "Name of Book" %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :pages, "Number of Pages" %>
        <%= f.number_field :pages %>
    </div>

    <div class="field">
        <%= f.label :genre, "Genre" %>
        <%= f.text_field :genre %>
    </div>
    <%= f.submit "Submit" %>
    <% end %>

app/views/books/show.html.erb
<h1><%= "#{@book.name} by #{@author.first_name} #{@author.last_name}"  %></h1>
<%= link_to("Back to #{@author.first_name} #{@author.last_name}", @author) %>

<br>
<br>

<h3><%= @book.genre %></h3>
<h3><%= "#{@book.pages} Pages" %></h3>

<%= link_to("Edit Book", edit_author_book_path(@author, @book)) %>
<%= link_to "Delete Book", author_book_path(@author, @book),
    data: {
        turbo_method: :delete, 
        turbo_confirm: "Are you sure you want to delete #{@book.name}?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>